# Generated by Django 5.1.6 on 2025-02-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0002_packagecreate_aprovel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('package', models.CharField(max_length=30)),
                ('number_of_people', models.IntegerField()),
                ('booking_date', models.DateField()),
                ('phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='packagecreate',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
