# Generated by Django 5.1.6 on 2025-03-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0003_bookingdetails_packagecreate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.usersign_up'),
        ),
        migrations.AddField(
            model_name='packagecreate',
            name='vendor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.vendorregister'),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='vendorregister',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
