# Generated by Django 5.1.6 on 2025-03-02 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0004_bookingdetails_user_packagecreate_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.usersign_up'),
        ),
    ]
