# Generated by Django 5.1.6 on 2025-03-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0005_alter_bookingdetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.usersign_up'),
        ),
        migrations.AlterField(
            model_name='packagecreate',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.vendorregister'),
        ),
    ]
