# Generated by Django 5.1.6 on 2025-03-02 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0008_alter_bookingdetails_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.packagecreate'),
        ),
    ]
