# Generated by Django 5.1.6 on 2025-03-02 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0010_alter_bookingdetails_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='package',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.packagecreate'),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.usersign_up'),
        ),
        migrations.AlterField(
            model_name='packagecreate',
            name='vendor',
            field=models.IntegerField(default=0),
        ),
    ]
