# Generated by Django 5.1.6 on 2025-03-02 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0011_alter_bookingdetails_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagecreate',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.vendorregister'),
        ),
    ]
