# Generated by Django 5.1.6 on 2025-03-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelbug_new', '0012_alter_packagecreate_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.packagecreate'),
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travelbug_new.usersign_up'),
        ),
    ]
